name: eRoomApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+17.9

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  numeric_keyboard:

  #Firebase Packages
  firebase_core:
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  firebase_storage: 

  #Notification Pacakges
  firebase_messaging:
  flutter_local_notifications:
  flutter_app_badger:

  #Image pick from library, crop image after pick image.
  image_picker:
  #multi_image_picker:
  file_picker:
  image_cropper:
  cached_network_image:

  photo_view:
  font_awesome_flutter:
  fluttertoast:
  share: any
  uuid: any
  footer: any
  google_fonts:
  email_validator:
  flutter_hooks:
  hovering:
  

  #ETC
  shared_preferences: 
  url_launcher:
  intl:

  http: 
  mobx: 
  flutter_mobx: 
  provider: 
  cupertino_icons: 
  permission_handler:
  carousel_slider:
  path_provider:
  flutter_bloc:
  rxdart:
  flutter_screenutil:
  basic_utils:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  #image_path: "assets/img/app_logo.png"
  image_path: "assets/img/eRoom.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/res/za.json
